repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v3.29.1"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.7.1"
    hooks:
      - id: nbstripout
        stages: [pre-commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v3.1.0"
    hooks:
      - id: prettier
        stages: [pre-commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.0"
    hooks:
      # Run the linter.
      - id: ruff
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
